/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Giaodien;

import javax.swing.JOptionPane;

/**
 *
 * @author lynnd
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_04 = new javax.swing.JLabel();
        btnqlnv_04 = new javax.swing.JButton();
        btntable_04 = new javax.swing.JButton();
        btnThongKe_04 = new javax.swing.JButton();
        btnfood_04 = new javax.swing.JButton();
        btnbh_04 = new javax.swing.JButton();
        jLabel2_04 = new javax.swing.JLabel();
        jLabel3_04 = new javax.swing.JLabel();
        jLabel4_04 = new javax.swing.JLabel();
        jLabel5_04 = new javax.swing.JLabel();
        jLabel6_04 = new javax.swing.JLabel();
        jMenuBar2_04 = new javax.swing.JMenuBar();
        jMenu1_04 = new javax.swing.JMenu();
        jMenuItem2_04 = new javax.swing.JMenuItem();
        jMenuItem1_04 = new javax.swing.JMenuItem();
        jMenuItem3_04 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cofe_1.jpg"))); // NOI18N
        jLabel1_04.setText("Cofe Never Be Alone");

        btnqlnv_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nhanvien.png"))); // NOI18N
        btnqlnv_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnv_04ActionPerformed(evt);
            }
        });

        btntable_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/table.png"))); // NOI18N

        btnThongKe_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/statistics.png"))); // NOI18N
        btnThongKe_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKe_04ActionPerformed(evt);
            }
        });

        btnfood_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/food.png"))); // NOI18N

        btnbh_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/order.png"))); // NOI18N

        jLabel2_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2_04.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2_04.setText("Quản lý nhân viên");

        jLabel3_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3_04.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3_04.setText("Bán Hàng");

        jLabel4_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4_04.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4_04.setText("Đồ uống/ thức ăn");

        jLabel5_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5_04.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5_04.setText("Thống kê");

        jLabel6_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6_04.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6_04.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6_04.setText("Bàn");

        jMenu1_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/istockphoto-1210939712-170667a.jpg"))); // NOI18N
        jMenu1_04.setText("Tài khoản");
        jMenu1_04.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem2_04.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem2_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jMenuItem2_04.setText("Thêm tài khoản");
        jMenuItem2_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_04ActionPerformed(evt);
            }
        });
        jMenu1_04.add(jMenuItem2_04);

        jMenuItem1_04.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem1_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        jMenuItem1_04.setText("Đổi mật khẩu");
        jMenuItem1_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_04ActionPerformed(evt);
            }
        });
        jMenu1_04.add(jMenuItem1_04);

        jMenuItem3_04.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuItem3_04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jMenuItem3_04.setText("Đăng xuất");
        jMenuItem3_04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_04ActionPerformed(evt);
            }
        });
        jMenu1_04.add(jMenuItem3_04);

        jMenuBar2_04.add(jMenu1_04);

        setJMenuBar(jMenuBar2_04);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1_04, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel5_04)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel6_04, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2_04, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnThongKe_04, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(btnqlnv_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnbh_04, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntable_04, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3_04)
                                .addGap(84, 84, 84)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4_04))
                            .addComponent(btnfood_04, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1_04, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbh_04)
                            .addComponent(btnqlnv_04)))
                    .addComponent(btnfood_04))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_04)
                    .addComponent(jLabel3_04)
                    .addComponent(jLabel4_04))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntable_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe_04))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5_04)
                    .addComponent(jLabel6_04))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_04ActionPerformed
        add_an_account add=new add_an_account();
        add.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jMenuItem2_04ActionPerformed

    private void jMenuItem3_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_04ActionPerformed
        JOptionPane.showMessageDialog(this,"Đã đăng xuất!");
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3_04ActionPerformed

    private void jMenuItem1_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_04ActionPerformed
       Change_pass change=new Change_pass();
       change.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jMenuItem1_04ActionPerformed

    private void btnThongKe_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKe_04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKe_04ActionPerformed

    private void btnqlnv_04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnv_04ActionPerformed
        Quanlynhanvien quanly=new Quanlynhanvien();
        quanly.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnqlnv_04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe_04;
    private javax.swing.JButton btnbh_04;
    private javax.swing.JButton btnfood_04;
    private javax.swing.JButton btnqlnv_04;
    private javax.swing.JButton btntable_04;
    private javax.swing.JLabel jLabel1_04;
    private javax.swing.JLabel jLabel2_04;
    private javax.swing.JLabel jLabel3_04;
    private javax.swing.JLabel jLabel4_04;
    private javax.swing.JLabel jLabel5_04;
    private javax.swing.JLabel jLabel6_04;
    private javax.swing.JMenu jMenu1_04;
    private javax.swing.JMenuBar jMenuBar2_04;
    private javax.swing.JMenuItem jMenuItem1_04;
    private javax.swing.JMenuItem jMenuItem2_04;
    private javax.swing.JMenuItem jMenuItem3_04;
    // End of variables declaration//GEN-END:variables
}
